_BASE_: "Base-TotalText.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "SyncBN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
    # Best e2e: 0.5; Best det: 0.4
    INFERENCE_TH_TEST: 0.5
INPUT:
  CROP:
    ENABLED: False
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  MAX_ITER: 4800
  CHECKPOINT_PERIOD: 1200
TEST:
  EVAL_PERIOD: 1200
OUTPUT_DIR: "output/batext/vintext/v2_attn_R_50"
